import { randomUUID } from "node:crypto";
import { chmod, rename, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const configSchema = z.object({
  account: z.string().min(1),
  outputPath: z.string().min(1),
  secretsItem: z.string().min(1),
  vault: z.string().min(1),
});

const itemSchema = z.object({
  fields: z
    .array(
      z.object({
        id: z.string().optional(),
        label: z.string().optional(),
        value: z.unknown().optional(),
      }),
    )
    .default([]),
});

const shellNamePattern = /^[A-Za-z_][A-Za-z0-9_]*$/;
const defaultOutputPath = fileURLToPath(
  new URL("../../.env.shell", import.meta.url),
);

const shellQuote = (value: string) => `'${value.replaceAll("'", `'\\''`)}'`;

const getConfig = () =>
  configSchema.parse({
    account: process.env.OP_ACCOUNT ?? "my.1password.com",
    outputPath: process.env.OP_ENV_SHELL_OUTPUT ?? defaultOutputPath,
    secretsItem: process.env.OP_OVERMUX_SECRETS_ITEM ?? "Overmux Secrets Local",
    vault: process.env.OP_VAULT ?? "Private",
  });

const getOnePasswordItem = (config: z.infer<typeof configSchema>) => {
  const result = spawnSync(
    "op",
    [
      "item",
      "get",
      config.secretsItem,
      "--account",
      config.account,
      "--vault",
      config.vault,
      "--format",
      "json",
    ],
    { encoding: "utf8", stdio: ["inherit", "pipe", "inherit"] },
  );
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error("Failed to get credentials from 1Password");
  }
  return itemSchema.parse(JSON.parse(result.stdout));
};

const renderEnvShell = (
  config: z.infer<typeof configSchema>,
  item: z.infer<typeof itemSchema>,
) => {
  const exports = item.fields
    .filter(({ id, label, value }) => {
      const renderedValue =
        value === undefined || value === null ? "" : String(value);
      return (
        id !== "notesPlain" &&
        label !== "notesPlain" &&
        Boolean(label && shellNamePattern.test(label)) &&
        Boolean(renderedValue.trim())
      );
    })
    .map(({ label, value }) => `export ${label}=${shellQuote(String(value))}`)
    .sort();
  return [
    `# Generated by scripts/write-local-dot-env.ts from 1Password item: ${config.secretsItem}`,
    "# Do not edit manually. Create .env.local.shell to override generated values locally.",
    "",
    ...exports,
    "",
  ].join("\n");
};

const main = async () => {
  const config = getConfig();
  const temporaryPath = `${config.outputPath}.tmp.${randomUUID()}`;
  console.error("Getting credentials from 1Password...");
  const content = renderEnvShell(config, getOnePasswordItem(config));
  try {
    await writeFile(temporaryPath, content, { flag: "wx", mode: 0o600 });
    await chmod(temporaryPath, 0o600);
    await rename(temporaryPath, config.outputPath);
  } catch (error) {
    await rm(temporaryPath, { force: true });
    throw error;
  }
  console.log(`Wrote ${process.env.OP_ENV_SHELL_OUTPUT ?? "../.env.shell"}`);
};

await main();
